DROP TABLE TBL_USER;
DROP SEQUENCE SEQ_USER;

--CREATE USER SEQUENCE
CREATE SEQUENCE SEQ_USER;
--CREATE USER TABLE
CREATE TABLE TBL_USER (
USER_NUM NUMBER(10), 	
ID VARCHAR2(50) NOT NULL, 
PASSWORD VARCHAR2(100) NOT NULL, 
NAME VARCHAR2(50) NOT NULL, 
SEX CHAR(1) NOT NULL, 
BIRTHDAY CHAR(10) NOT NULL, 
ADDRESS VARCHAR2(100) NOT NULL, 
PHONE VARCHAR2(50) NOT NULL, 
EMAIL VARCHAR2(50) NOT NULL, 
REG_DATE DATE DEFAULT SYSDATE, 		
UPDATE_DATE DATE DEFAULT SYSDATE, 		
ENABLED CHAR(1) DEFAULT '1', 
CONSTRAINT PK_USER PRIMARY KEY(USER_NUM)
);

--INSERT INTO USER TABLE
INSERT INTO TBL_USER 
(USER_NUM, ID, PASSWORD, NAME, SEX, BIRTHDAY, ADDRESS, PHONE, EMAIL, REG_DATE)
VALUES
(SEQ_USER.NEXTVAL, 'MASTER', 'MASTER', 'ANOLD', 'M', '2000-01-01', 'REPUBLIC OF KOREA', 
 '010-1234-5678', 'ANOLD@NAVER.COM', SYSDATE);
INSERT INTO TBL_USER 
(USER_NUM, ID, PASSWORD, NAME, SEX, BIRTHDAY, ADDRESS, PHONE, EMAIL, REG_DATE)
VALUES
(SEQ_USER.NEXTVAL, 'SUB', 'SUB', 'ANOLD', 'M', '2000-01-01', 'REPUBLIC OF KOREA', 
 '010-1234-5678', 'ANOLD@NAVER.COM', SYSDATE);

--FULL SCAN에서 FAST FULL SCAN으로 바뀜
CREATE INDEX IDX_USER_ID ON TBL_USER(ID, PASSWORD);
